version: '3.7'
name: messy-stack

networks:
  internal:
    internal: true

services:
  edtunnel:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    networks:
      - internal
    restart: unless-stopped

  v2ray:
    image: teddysun/v2ray:latest
    networks:
      - default
      - internal
    ports:
      - '${PORT}:10086'
    volumes:
      - './v2ray-config.json:/etc/v2ray/config.json:ro'
    restart: unless-stopped
    depends_on:
      edtunnel:
        condition: service_healthy
